FROM python:3-alpine

RUN pip install --no-cache-dir gwbackupy
RUN apk add --no-cache bash

ENV GWBACKUPY_WORKDIR="/data"
ENV GWBACKUPY_APPDIR="/app"
ENV GWBACKUPY_ACCOUNT_EMAILS="example@example.com example2@example.com"
#ENV GWBACKUPY_CRON_FULL_SYNC="0 0 * * 0"
#ENV GWBACKUPY_CRON_QUCIK_SYNC="0 0 * * 1-6"
ENV GWBACKUPY_CRON_FULL_SYNC="*/2 * * * *"
ENV GWBACKUPY_CRON_QUCIK_SYNC="* * * * *"
ENV GWBACKUPY_CRON_LOG="${GWBACKUPY_APPDIR}/crontab.log"
ENV GWBACKUPY_CRONTAB="${GWBACKUPY_APPDIR}/crontab"

VOLUME ${GWBACKUPY_WORKDIR}
WORKDIR ${GWBACKUPY_APPDIR}
COPY ./full-sync.sh ${GWBACKUPY_APPDIR}/
COPY ./quick-sync.sh ${GWBACKUPY_APPDIR}/
RUN touch ${GWBACKUPY_CRON_LOG}
RUN echo "${GWBACKUPY_CRON_FULL_SYNC} /bin/bash ${GWBACKUPY_APPDIR}/full-sync.sh >> ${GWBACKUPY_CRON_LOG} 2>&1" > ${GWBACKUPY_CRONTAB}
RUN echo "${GWBACKUPY_CRON_QUCIK_SYNC} /bin/bash ${GWBACKUPY_APPDIR}/quick-sync.sh >> ${GWBACKUPY_CRON_LOG} 2>&1" >> ${GWBACKUPY_CRONTAB}
RUN crontab ${GWBACKUPY_CRONTAB}
RUN crontab -l
#CMD crond -f && tail -f ${GWBACKUPY_CRON_LOG}
CMD crond && tail -f ${GWBACKUPY_CRON_LOG}
#ENTRYPOINT ["python", "-m", "gwbackupy", "--workdir=${GWBACKUPY_WORKDIR}"]